name: deployment heroku

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]
        mongodb-version: [4.2]

    steps:
      - uses: actions/checkout@v2
      - name: Staging deploy
      run: |
        git push -f https://heroku:${{ secrets.HEROKU_API_TOKEN }}@git.heroku.com/bot-achivement.git master